let result = ['', 'Avis', 'de', 'recrutement:', 'Comptable', ''][
  ('', 'Avis', 'de', 'recrutement:', 'Comptable', '')
][
  ('', 'Offre', "d'emploi:", 'Superviseur', 'Mobilisation', 'Communautaire', '')
][
  ('', 'Offre', "d'emploi:", 'Superviseur', 'Mobilisation', 'Communautaire', '')
][('', 'Recrutement', 'de', 'plusieurs', 'profils', '')][
  ('', 'Recrutement', 'de', 'plusieurs', 'profils', '')
][('', 'Avis', 'de', 'recrutement:', 'Secrétaire', 'Bilingue', '')][
  ('', 'Avis', 'de', 'recrutement:', 'Secrétaire', 'Bilingue', '')
][
  ('',
  'Offre',
  "d'emploi:",
  'Vendeur',
  'Coursier',
  'pour',
  'vente',
  'des',
  'Chips',
  '')
][
  ('',
  'Offre',
  "d'emploi:",
  'Vendeur',
  'Coursier',
  'pour',
  'vente',
  'des',
  'Chips',
  '')
][('', 'HEMS', 'ENGINEERING', 'CORE', 'LTD', 'is', 'recruting', '')][
  ('', 'HEMS', 'ENGINEERING', 'CORE', 'LTD', 'is', 'recruting', '')
][
  ('',
  'Job',
  'opportunities',
  'at',
  'the',
  'National',
  'Employment',
  'Fund',
  '(NEF)',
  '')
][
  ('',
  'Job',
  'opportunities',
  'at',
  'the',
  'National',
  'Employment',
  'Fund',
  '(NEF)',
  '')
][('', 'MOBITRANSFERT', 'recherche', 'plusieurs', 'Commerciaux', '')][
  ('', 'MOBITRANSFERT', 'recherche', 'plusieurs', 'Commerciaux', '')
][
  ('',
  'Avis',
  'de',
  'recrutement:',
  'Employé(e)',
  'polyvalent',
  'de',
  'pressing',
  '(H/F)',
  '')
][
  ('',
  'Avis',
  'de',
  'recrutement:',
  'Employé(e)',
  'polyvalent',
  'de',
  'pressing',
  '(H/F)',
  '')
][
  ('',
  'La',
  'Garantie',
  'Mutuelle',
  'des',
  'Cadres',
  '(GMC',
  'S.A)',
  'recrute',
  '!',
  '')
][
  ('',
  'La',
  'Garantie',
  'Mutuelle',
  'des',
  'Cadres',
  '(GMC',
  'S.A)',
  'recrute',
  '!',
  '')
][('', 'Offre', "d'emploi:", 'Réceptionniste', 'de', 'pressing', '')][
  ('', 'Offre', "d'emploi:", 'Réceptionniste', 'de', 'pressing', '')
][
  ('',
  'Avis',
  'de',
  'recrutement:',
  '10',
  'postes',
  'vacants',
  '-',
  'PACSSA',
  'FOOD',
  '')
][
  ('',
  'Avis',
  'de',
  'recrutement:',
  '10',
  'postes',
  'vacants',
  '-',
  'PACSSA',
  'FOOD',
  '')
][('', 'UCB', 'recrute', 'un', 'directeur', 'QHSE', '')][
  ('', 'UCB', 'recrute', 'un', 'directeur', 'QHSE', '')
][
  ('',
  'Avis',
  "d'appel",
  'à',
  'candidature',
  'pour',
  'la',
  'sélection',
  'et',
  'la',
  'Formation',
  'des',
  'Formateurs',
  'des',
  'Centres',
  'de',
  'Formation',
  'aux',
  'Métiers',
  '')
][
  ('',
  'Avis',
  "d'appel",
  'à',
  'candidature',
  'pour',
  'la',
  'sélection',
  'et',
  'la',
  'Formation',
  'des',
  'Formateurs',
  'des',
  'Centres',
  'de',
  'Formation',
  'aux',
  'Métiers',
  '')
][
  ('',
  'Avis',
  'de',
  'recrutement',
  ':',
  'Un',
  'Mécanicien',
  'automobile,',
  'un',
  'électricien',
  'automobile',
  'et',
  'une',
  'secrétaire',
  '')
][
  ('',
  'Avis',
  'de',
  'recrutement',
  ':',
  'Un',
  'Mécanicien',
  'automobile,',
  'un',
  'électricien',
  'automobile',
  'et',
  'une',
  'secrétaire',
  '')
][
  ('',
  'Offre',
  "d'emploi:",
  'Responsable',
  'Mécanique',
  'Chaudronnerie',
  '-',
  'SOSUCAM',
  '')
][
  ('',
  'Offre',
  "d'emploi:",
  'Responsable',
  'Mécanique',
  'Chaudronnerie',
  '-',
  'SOSUCAM',
  '')
][('', 'Citibank', 'Cameroon', 'recrute', ':', '02', 'postes', 'vacants', '')][
  ('', 'Citibank', 'Cameroon', 'recrute', ':', '02', 'postes', 'vacants', '')
][
  ('',
  'Job',
  'Opportunity:',
  'Business',
  'Analysis',
  '/',
  'Client',
  'Services',
  '')
][
  ('',
  'Job',
  'Opportunity:',
  'Business',
  'Analysis',
  '/',
  'Client',
  'Services',
  '')
][('', 'Job', 'Opportunity:', 'Projet', 'Manager', 'at', 'Citi', 'Bank', '')][
  ('', 'Job', 'Opportunity:', 'Projet', 'Manager', 'at', 'Citi', 'Bank', '')
][
  ('',
  'Recrutement',
  'massif',
  'au',
  'Fond',
  'National',
  'de',
  "l'Emploi",
  '(FNE)',
  '')
][
  ('',
  'Recrutement',
  'massif',
  'au',
  'Fond',
  'National',
  'de',
  "l'Emploi",
  '(FNE)',
  '')
];
